<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #222; margin: 0; padding: 0; }
        .header { background: #1a472a; color: #fff; padding: 20px 32px; text-align: center; }
        .header .ganesh-img { width: 80px; height: 80px; object-fit: contain; margin-bottom: 8px; }
        .header .mantra { font-size: 18px; font-weight: bold; letter-spacing: 1px; margin: 0 0 4px; }
        .header p { margin: 4px 0 0; font-size: 13px; opacity: 0.8; }
        .section { padding: 24px 32px; }
        .customer-info { background: #f8f9fa; border: 1px solid #e0e0e0; border-radius: 6px; padding: 16px 20px; margin-bottom: 24px; }
        .customer-info table { width: 100%; border-collapse: collapse; }
        .customer-info td { padding: 5px 10px; font-size: 13px; }
        .customer-info td:first-child { font-weight: bold; width: 140px; color: #555; }
        .module-badge { display: inline-block; background: #1a472a; color: #fff; padding: 4px 12px; border-radius: 12px; font-size: 12px; margin-bottom: 16px; }
        .subcategory { margin-bottom: 28px; }
        .subcategory h3 { font-size: 15px; color: #1a472a; border-bottom: 2px solid #1a472a; padding-bottom: 6px; margin-bottom: 12px; }
        .remedy-group { margin-bottom: 18px; }
        .remedy-label { font-size: 11px; font-weight: bold; text-transform: uppercase; color: #fff; background: #2d6a4f; display: inline-block; padding: 2px 10px; border-radius: 4px; margin-bottom: 8px; letter-spacing: 0.5px; }
        .solution { margin-bottom: 12px; padding: 12px 16px; background: #f9fafb; border-left: 3px solid #1a472a; }
        .solution h4 { margin: 0 0 6px; font-size: 13px; color: #333; }
        .solution p { margin: 0; font-size: 12px; color: #555; line-height: 1.6; }
        .footer { text-align: center; font-size: 11px; color: #999; padding: 16px 32px; border-top: 1px solid #eee; margin-top: 16px; }
    </style>
</head>
<body>
    <div class="header">
        <img class="ganesh-img" src="file://{{ str_replace('\\', '/', public_path('uploads/ganeshji_image.jfif')) }}" alt="Ganesh" />
        <div class="mantra">Om Ganeshaye Namah</div>
        <p>Generated by {{ $client->name }} &nbsp;|&nbsp; {{ now()->format('d M Y') }}</p>
    </div>

    <div class="section">
        <div class="module-badge">{{ $module }} Module</div>

        <div class="customer-info">
            <table>
                <tr><td>Name</td><td>{{ $customer['first_name'] }} {{ $customer['last_name'] }}</td></tr>
                <tr><td>Date of Birth</td><td>{{ \Carbon\Carbon::parse($customer['dob'])->format('d M Y') }}</td></tr>
                <tr><td>Contact</td><td>{{ $customer['contact'] }}</td></tr>
            </table>
        </div>

        @foreach($subcategories as $sub)
        <div class="subcategory">
            <h3>{{ $sub->name }}</h3>
            @if($sub->description)
                <p style="font-size:12px;color:#666;margin-bottom:10px;">{{ $sub->description }}</p>
            @endif
            @php $grouped = $sub->solutions->groupBy('remedy_type'); @endphp
            @if($grouped->isEmpty())
                <p style="font-size:12px;color:#999;">No solutions available for this area.</p>
            @else
                @foreach($grouped as $remedyType => $solutions)
                <div class="remedy-group">
                    <span class="remedy-label">{{ $remedyType }}</span>
                    @foreach($solutions as $solution)
                    <div class="solution">
                        <h4>{{ $solution->title }}</h4>
                        <div>{!! $solution->content !!}</div>
                    </div>
                    @endforeach
                </div>
                @endforeach
            @endif
        </div>
        @endforeach
    </div>

    <div class="footer">
        Reiki Healing Assam &mdash; Developed by ITNext Solutions &mdash; Confidential Report
    </div>
</body>
</html>
