@extends('adminlte::page')

@section('title', 'Generated Reports')

@section('content_header')
    <h1>Generated Reports</h1>
@stop

@section('content')
@if(session('success'))
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ session('success') }}
    </div>
@endif

<div class="card">
    <div class="card-body p-0">
        <table class="table table-hover table-sm mb-0">
            <thead class="thead-light">
                <tr>
                    <th>#</th>
                    <th>Customer Name</th>
                    <th>Date of Birth</th>
                    <th>Contact</th>
                    <th>Category</th>
                    <th>Generated By</th>
                    <th>Date</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @forelse($reports as $report)
                <tr>
                    <td>{{ $reports->firstItem() + $loop->index }}</td>
                    <td><strong>{{ $report->customer_first_name }} {{ $report->customer_last_name }}</strong></td>
                    <td>{{ $report->customer_dob->format('d M Y') }}</td>
                    <td>{{ $report->customer_contact }}</td>
                    <td><span class="badge badge-info">{{ $report->module }}</span></td>
                    <td>{{ $report->client->name ?? '—' }}</td>
                    <td>{{ $report->created_at->format('d M Y, h:i A') }}</td>
                    <td>
                        <a href="{{ route('admin.reports.show', $report) }}" class="btn btn-xs btn-info">
                            <i class="fas fa-eye"></i>
                        </a>
                        <form action="{{ route('admin.reports.destroy', $report) }}" method="POST" class="d-inline"
                              onsubmit="return confirm('Delete this report record?')">
                            @csrf @method('DELETE')
                            <button class="btn btn-xs btn-danger"><i class="fas fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
                @empty
                <tr><td colspan="8" class="text-center text-muted py-3">No reports generated yet.</td></tr>
                @endforelse
            </tbody>
        </table>
    </div>
    @if($reports->hasPages())
    <div class="card-footer">
        {{ $reports->links() }}
    </div>
    @endif
</div>
@stop

@push('js')
<form id="logout-form" action="{{ route('admin.logout') }}" method="POST" class="d-none">@csrf</form>
@endpush
