@extends('adminlte::page')

@section('title', 'Report Details')

@section('content_header')
    <div class="d-flex justify-content-between align-items-center">
        <h1>Report Details</h1>
        <a href="{{ route('admin.reports.index') }}" class="btn btn-secondary btn-sm">
            <i class="fas fa-arrow-left"></i> Back
        </a>
    </div>
@stop

@section('content')
<div class="row">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header"><h6 class="mb-0">Customer Info</h6></div>
            <div class="card-body p-0">
                <table class="table table-sm table-borderless mb-0">
                    <tr>
                        <th class="pl-3" style="width:130px;color:#555;">Name</th>
                        <td>{{ $report->customer_first_name }} {{ $report->customer_last_name }}</td>
                    </tr>
                    <tr>
                        <th class="pl-3" style="color:#555;">Date of Birth</th>
                        <td>{{ $report->customer_dob->format('d M Y') }}</td>
                    </tr>
                    <tr>
                        <th class="pl-3" style="color:#555;">Contact</th>
                        <td>{{ $report->customer_contact }}</td>
                    </tr>
                    <tr>
                        <th class="pl-3" style="color:#555;">Category</th>
                        <td><span class="badge badge-info">{{ $report->module }}</span></td>
                    </tr>
                    <tr>
                        <th class="pl-3" style="color:#555;">Generated By</th>
                        <td>{{ $report->client->name ?? '—' }}</td>
                    </tr>
                    <tr>
                        <th class="pl-3" style="color:#555;">Generated On</th>
                        <td>{{ $report->created_at->format('d M Y, h:i A') }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    <div class="col-md-8">
        @forelse($subcategories as $sub)
        <div class="card mb-3">
            <div class="card-header bg-dark text-white py-2">
                <strong>{{ $sub->name }}</strong>
                <span class="badge badge-warning ml-2">{{ $sub->solutions->count() }} {{ Str::plural('remedy', $sub->solutions->count()) }}</span>
            </div>
            <div class="card-body p-0">
                @php $grouped = $sub->solutions->groupBy('remedy_type'); @endphp
                @foreach($grouped as $type => $solutions)
                <div class="px-3 pt-3 pb-2">
                    @php
                        $colors = [
                            'Crystal'           => ['badge-success',  '#f0fdf4', '#166534'],
                            'Lal Kitab'         => ['badge-warning',  '#fff7ed', '#9a3412'],
                            'Switch Word'       => ['badge-purple',   '#faf5ff', '#6b21a8'],
                            'Vedic Switch Word' => ['badge-info',     '#fefce8', '#854d0e'],
                        ];
                        $c = $colors[$type] ?? ['badge-secondary', '#f9fafb', '#374151'];
                    @endphp
                    <span class="badge {{ $c[0] }} mb-2" style="font-size:12px;">{{ $type }}</span>
                    @foreach($solutions as $sol)
                    <div class="rounded p-3 mb-2" style="background:{{ $c[1] }};border:1px solid rgba(0,0,0,0.07);">
                        <strong style="color:{{ $c[2] }};">{{ $sol->title }}</strong>
                        <div class="mt-1" style="color:{{ $c[2] }};opacity:0.85;font-size:13px;">{!! $sol->content !!}</div>
                    </div>
                    @endforeach
                </div>
                @endforeach
                @if($sub->solutions->isEmpty())
                    <p class="px-3 py-2 text-muted text-sm">No remedies.</p>
                @endif
            </div>
        </div>
        @empty
        <div class="alert alert-warning">No subcategory data found for this report.</div>
        @endforelse
    </div>
</div>
@stop

@push('js')
<form id="logout-form" action="{{ route('admin.logout') }}" method="POST" class="d-none">@csrf</form>
@endpush
